namespace MAModels.Enumerables
{
    public enum EMovieTags
    {
        Animazione =1,
        Avventura =2,
        Azione =3,
        Biografico =4,
        Commedia =5,
        Documentario =6,
        Drammatico =7,
        Erotico =8,
        Fantascienza =9,
        FantasyFantastico =10, 
        Guerra =11,
        Horror =12,
        Musical =13,
        Storico =14,
        Thriller =15,
        Western =16,
        Catastrofico =17,
        Comico =18,
        Epico =19,
        Giallo =20,
        Grottesco =21,
        Mitologico =22,
        Noir =23,
        Politico =24,
        Poliziesco =25,
        Protogiallo =26,
        Biblico =27,
        BuddyCop =28,
        Religioso =29,
        Sentimentale =30,
        Spionaggio =31,
        Sportivo =32,
        SpaceOpera =33,
    }
}
